### ISSUE TITLE
FE GitHub Actions 배포 오류를 수정한다

### ISSUE THREAD

**Issue by solo5star** [woowacourse/prolog#1271]
## 문제 상황

<img src="https://user-images.githubusercontent.com/20203944/236747845-b61c987d-9b97-4b1d-9e62-ee889c85bcee.png" height="400">

* FE 빌드가 의존성 오류로 인해 배포가 제대로 수행되지 않고 있다.
* Install Dependencies(`yarn`)가 cache hit 여부와 상관없이 수행되고 있다.

<br><br>

## 개선할 내용

1. cache hit 이 된 경우엔 Install Dependencies 단계를 건너뛰도록 하여 개선한다.
2. Install Dependencies 수행 시 `yarn` 대신 `yarn install --frozen-lockfile` 로 수행하도록 한다.

```yml
      - name: Install dependencies
        run: yarn --frozen-lockfile
        # cache hit이 발생한 경우 (즉 package-lock.json이 변경되지 않은 경우)
        # Install dependencies 실행은 skip 됩니다.
        if: steps.cache.outputs.cache-hit != 'true'
```

<br><br>

## 참고 자료

* https://solo5star.tistory.com/36
